### ISSUE TITLE
Wrong orientation and malfunctioning of the buttons in Tenn board

### ISSUE THREAD

**Issue by T3nk4I** [T3nk4I/Minisumo#1]
The OLED Screen Direction in the Tenn Board covers the buttons instead of the arduino nano as planned.
The push buttons don't pass current to the MCU, thus not detecting the input, making the buttons obsolete.

**Comment by AT4NI** [comment]
Buttons do not work, do it again.
RECOMMEND to use pull down configuration

**Comment by T3nk4I** [comment]
Tenn rev2.2 is now avaiable, (gerber files soon), fixes the buttons not working, the screen orientation and replaces the tantalum capacitors with more avaiable 0805 package capacitors, also uses a pin socket switch that should support up to 50V, so now it's possible to use the board with 6S (yet to be tested).
